### ISSUE TITLE
Output doesn't work

### ISSUE THREAD

**Issue by Sigton** [PigeonScript/pigeon-script-js#4]
Seems to be a problem with output, can someone who knows JS better look at it?

Sigton

**Comment by SilversApprentice** [comment]
I'll take a look at it

**Comment by SilversApprentice** [comment]
Found it - it seems you forgot that js syntax is `Math.pow()`, not `pow()` :P I'll fix it, I planned to update it anyway

**Comment by SilversApprentice** [comment]
I'm uploading the fixed one now, I also edited a bit of formatting. Feel free to make a new issue if something comes up
